@url = http://localhost:3000/filmes
GET {{url}}

###
GET {{url}}/2

###
POST {{url}}
Content-Type: application/json

{
  "titulo": "Paulo Capão", 
  "ano": 2007, 
  "assistido": true, 
  "diretor": "Paul" 
}

###
PUT {{url}}/3
Content-Type: application/json

{
  "ano": 2006 
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "concluida" : true
}

###
DELETE {{url}}/2
